import { Roboto } from "next/font/google"; // Import Roboto font
import "./globals.css";
import LayoutWrapper from "./LayoutWrapper"; // Import the client component
import { AuthProvider } from "@/context/AuthContext";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"], // Choose the font weights you need
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Rahul Nagar",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png", // Path to favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo2.png" type="image/png" />
      </head>
      <body
        className={`${roboto.variable} antialiased bg-gradient-to-r from-[#220E31] via-[#29133A] to-[#241033]`}
      >
        <AuthProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
